version: '3.8'

services:
  db:
    image: postgres
    container_name: puzzlezone_postgres
    volumes:
      - ../../postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build:
      context: ..
      dockerfile: Deployment/Dockerfile-web-debug
    container_name: puzzlezone_web
    volumes:
      - ..:/app
    command: ['python','manage-test.py','runserver','0.0.0.0:8000']
    ports:
        - "8000:8000"
    depends_on:
        - db
        - rabbit
  worker:
    privileged: true
    build:
      context: ..
      dockerfile: Deployment/Dockerfile-celery-worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # expose the docker socket
    depends_on:
      - rabbit
      - db
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    container_name: puzzlezone_rabbit
    environment:
        - RABBITMQ_DEFAULT_USER=rabbit
        - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
        - "5672:5672"
