# Generated by Django 3.1 on 2020-08-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='result',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='submission',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
