# Generated by Django 3.0.2 on 2020-04-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_cases',
            field=models.CharField(max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='audited',
            field=models.CharField(choices=[('1', 'Submitted'), ('2', 'Accepted'), ('0', 'Draft')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='pre_solution',
            field=models.CharField(max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.CharField(max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution_code',
            field=models.CharField(max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_code',
            field=models.CharField(max_length=65536, null=True),
        ),
        migrations.DeleteModel(
            name='Testcase',
        ),
    ]
