# Generated by Django 3.0.2 on 2020-05-27 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_auto_20200416_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='submission',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='pre_solution',
            field=models.CharField(blank=True, max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.CharField(blank=True, max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution_code',
            field=models.CharField(blank=True, max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_cases',
            field=models.CharField(blank=True, max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_code',
            field=models.CharField(blank=True, max_length=65536, null=True),
        ),
    ]
