# Generated by Django 3.1 on 2020-08-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_auto_20200813_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, default='', max_length=8192),
        ),
        migrations.AlterField(
            model_name='question',
            name='pre_solution',
            field=models.CharField(blank=True, default='', max_length=8192),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.CharField(blank=True, default='', max_length=8192),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution_code',
            field=models.CharField(blank=True, default='', max_length=8192),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_cases',
            field=models.CharField(blank=True, default='', max_length=65536),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_code',
            field=models.CharField(blank=True, default='', max_length=8192),
        ),
    ]
