# Generated by Django 3.0.2 on 2020-05-29 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puzzle', '0003_auto_20200526_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='have_solution',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Question_edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=2048, null=True)),
                ('description', models.CharField(blank=True, max_length=65536, null=True)),
                ('pre_solution', models.CharField(blank=True, max_length=65536, null=True)),
                ('test_code', models.CharField(blank=True, max_length=65536, null=True)),
                ('test_cases', models.CharField(blank=True, max_length=65536, null=True)),
                ('solution', models.CharField(blank=True, max_length=65536, null=True)),
                ('solution_code', models.CharField(blank=True, max_length=65536, null=True)),
                ('solution_threshold', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle.Question')),
            ],
        ),
    ]
